### ISSUE TITLE
Header style mappings

### ISSUE THREAD

**Issue by antononcube** [kubaPod/M2MD#1]
Currently sections are mapped header 4. I think this mapping is preferable:

```
StyleToElement[style_]:= Switch[style
, "Title",         "h1"
, "Subtitle",      "**h2**" (* Bold h2 *)
, "Subsubtitle",   "**h3**" (* Bold h3 *)
, "Section",       "h2"
, "Subsection",    "h3"
, "Subsubsection", "h4"
, _ , "Text"
]
```

**Comment by kubaPod** [comment]
That is subjective but I think I agree. Current translation is just the first quick that came to my mind. I will change it but I will also add a way to easily specify it from user side. 

Thanks
