### ISSUE TITLE
String replacements of \[Rule] & co. do not work 

### ISSUE THREAD

**Issue by antononcube** [kubaPod/M2MD#2]
I see that `ProcessMDString` is implemented and applied in `M2MD[nb_NotebookObject,__]` but when I export to Markdown I still see "\[Rule]" and similar in the Markdown file.

(Also, maybe it is a good idea to have these string replacements specified with an option.)

**Comment by kubaPod** [comment]
Yes, I noticed. I need to investigate why named characters still sometimes appear in MD. Could you paste an example of a cell which is affected by this? 

More options and ways that users will be able to affect different stages of conversion are coming. I first need to clean up the ugly prototype code but with each prerelease I am closer to this goal.
